general:
  project_name: 202309-rsna-atd
  exp_name: exp001
  base_path: ec2
  data_path: data
  seed: 42

data:
  n_folds: 5
  # fold_i: [0, 1, 2, 3, 4]
  fold_i: [0]
  batch_size: 16
  batch_size_inference: 8
  stride: 100

model:
  model_name: tf_efficientnetv2_s
  pretrained: True
  in_chans: 1
  num_classes: 0 # to use as backbone
  global_pool: max
  hidden_dim: 128
  p_dropout: 0.3
  lr: 1e-4

pl_params:
  accelerator: auto
  max_epochs: 5
  enable_progress_bar: True
